(TeX-add-style-hook "Dummy"
 (lambda ()
    (TeX-run-style-hooks
     "url"
     "listings"
     "hypcap"
     "all"
     "hyperref"
     "subfigure"
     "fontenc"
     "T1"
     "xcolor"
     "table"
     "lscape"
     "pdflscape"
     "textcomp"
     "natbib"
     "setspace"
     "fancyhdr"
     "ltablex"
     "fancybox"
     "enumerate"
     "amsfonts"
     "amsthm"
     "amssymb"
     "amsmath"
     "graphicx"
     "debugshow"
     "final"
     "latex2e"
     "art11"
     "article"
     "11pt"
     "letterpaper")))

