(TeX-add-style-hook "full_course"
 (lambda ()
    (TeX-add-symbols
     '("blurb" 1)
     '("myMargin" 1)
     "margin")
    (TeX-run-style-hooks
     "listings"
     "hypcap"
     "all"
     "cclicenses"
     "hyperref"
     "subfigure"
     "fontenc"
     "T1"
     "xcolor"
     "table"
     "lscape"
     "pdflscape"
     "textcomp"
     "multicol"
     "rotating"
     "natbib"
     "setspace"
     "fancyhdr"
     "ltablex"
     "fancybox"
     "staves"
     "enumerate"
     "amsfonts"
     "amsthm"
     "amssymb"
     "amsmath"
     "graphicx"
     "debugshow"
     "final"
     "latex2e"
     "art10"
     "article"
     "10wpt"
     "letterpaper"
     "./1_Introduction/Introduction"
     "./2_BasicContent/Basic"
     "./3_FullContent/full"
     "./4_Math/math"
     "./5_Misc/misc")))

